export type KanaCard = {
  character: string
  answers: string[]
}

export const HIRAGANA_CARDS: KanaCard[] = [
  { character: 'あ', answers: ['a'] },
  { character: 'い', answers: ['i'] },
  { character: 'う', answers: ['u'] },
  { character: 'え', answers: ['e'] },
  { character: 'お', answers: ['o'] },
  { character: 'か', answers: ['ka'] },
  { character: 'き', answers: ['ki'] },
  { character: 'く', answers: ['ku'] },
  { character: 'け', answers: ['ke'] },
  { character: 'こ', answers: ['ko'] },
  { character: 'さ', answers: ['sa'] },
  { character: 'し', answers: ['shi', 'si'] },
  { character: 'す', answers: ['su'] },
  { character: 'せ', answers: ['se'] },
  { character: 'そ', answers: ['so'] },
  { character: 'た', answers: ['ta'] },
  { character: 'ち', answers: ['chi', 'ti'] },
  { character: 'つ', answers: ['tsu', 'tu'] },
  { character: 'て', answers: ['te'] },
  { character: 'と', answers: ['to'] },
  { character: 'な', answers: ['na'] },
  { character: 'に', answers: ['ni'] },
  { character: 'ぬ', answers: ['nu'] },
  { character: 'ね', answers: ['ne'] },
  { character: 'の', answers: ['no'] },
  { character: 'は', answers: ['ha'] },
  { character: 'ひ', answers: ['hi'] },
  { character: 'ふ', answers: ['fu', 'hu'] },
  { character: 'へ', answers: ['he'] },
  { character: 'ほ', answers: ['ho'] },
  { character: 'ま', answers: ['ma'] },
  { character: 'み', answers: ['mi'] },
  { character: 'む', answers: ['mu'] },
  { character: 'め', answers: ['me'] },
  { character: 'も', answers: ['mo'] },
  { character: 'や', answers: ['ya'] },
  { character: 'ゆ', answers: ['yu'] },
  { character: 'よ', answers: ['yo'] },
  { character: 'ら', answers: ['ra'] },
  { character: 'り', answers: ['ri'] },
  { character: 'る', answers: ['ru'] },
  { character: 'れ', answers: ['re'] },
  { character: 'ろ', answers: ['ro'] },
  { character: 'わ', answers: ['wa'] },
  { character: 'を', answers: ['wo', 'o'] },
  { character: 'ん', answers: ['n'] },
  { character: 'が', answers: ['ga'] },
  { character: 'ぎ', answers: ['gi'] },
  { character: 'ぐ', answers: ['gu'] },
  { character: 'げ', answers: ['ge'] },
  { character: 'ご', answers: ['go'] },
  { character: 'ざ', answers: ['za'] },
  { character: 'じ', answers: ['ji', 'zi'] },
  { character: 'ず', answers: ['zu'] },
  { character: 'ぜ', answers: ['ze'] },
  { character: 'ぞ', answers: ['zo'] },
  { character: 'だ', answers: ['da'] },
  { character: 'ぢ', answers: ['ji', 'di'] },
  { character: 'づ', answers: ['zu', 'du'] },
  { character: 'で', answers: ['de'] },
  { character: 'ど', answers: ['do'] },
  { character: 'ば', answers: ['ba'] },
  { character: 'び', answers: ['bi'] },
  { character: 'ぶ', answers: ['bu'] },
  { character: 'べ', answers: ['be'] },
  { character: 'ぼ', answers: ['bo'] },
  { character: 'ぱ', answers: ['pa'] },
  { character: 'ぴ', answers: ['pi'] },
  { character: 'ぷ', answers: ['pu'] },
  { character: 'ぺ', answers: ['pe'] },
  { character: 'ぽ', answers: ['po'] },
  { character: 'きゃ', answers: ['kya'] },
  { character: 'きゅ', answers: ['kyu'] },
  { character: 'きょ', answers: ['kyo'] },
  { character: 'しゃ', answers: ['sha', 'sya'] },
  { character: 'しゅ', answers: ['shu', 'syu'] },
  { character: 'しょ', answers: ['sho', 'syo'] },
  { character: 'ちゃ', answers: ['cha', 'tya', 'cya'] },
  { character: 'ちゅ', answers: ['chu', 'tyu', 'cyu'] },
  { character: 'ちょ', answers: ['cho', 'tyo', 'cyo'] },
  { character: 'にゃ', answers: ['nya'] },
  { character: 'にゅ', answers: ['nyu'] },
  { character: 'にょ', answers: ['nyo'] },
  { character: 'ひゃ', answers: ['hya'] },
  { character: 'ひゅ', answers: ['hyu'] },
  { character: 'ひょ', answers: ['hyo'] },
  { character: 'みゃ', answers: ['mya'] },
  { character: 'みゅ', answers: ['myu'] },
  { character: 'みょ', answers: ['myo'] },
  { character: 'りゃ', answers: ['rya'] },
  { character: 'りゅ', answers: ['ryu'] },
  { character: 'りょ', answers: ['ryo'] },
  { character: 'ぎゃ', answers: ['gya'] },
  { character: 'ぎゅ', answers: ['gyu'] },
  { character: 'ぎょ', answers: ['gyo'] },
  { character: 'じゃ', answers: ['ja', 'jya', 'zya'] },
  { character: 'じゅ', answers: ['ju', 'jyu', 'zyu'] },
  { character: 'じょ', answers: ['jo', 'jyo', 'zyo'] },
  { character: 'ぢゃ', answers: ['ja', 'dya'] },
  { character: 'ぢゅ', answers: ['ju', 'dyu'] },
  { character: 'ぢょ', answers: ['jo', 'dyo'] },
  { character: 'びゃ', answers: ['bya'] },
  { character: 'びゅ', answers: ['byu'] },
  { character: 'びょ', answers: ['byo'] },
  { character: 'ぴゃ', answers: ['pya'] },
  { character: 'ぴゅ', answers: ['pyu'] },
  { character: 'ぴょ', answers: ['pyo'] },
]

export const KATAKANA_CARDS: KanaCard[] = [
  { character: 'ア', answers: ['a'] },
  { character: 'イ', answers: ['i'] },
  { character: 'ウ', answers: ['u'] },
  { character: 'エ', answers: ['e'] },
  { character: 'オ', answers: ['o'] },
  { character: 'カ', answers: ['ka'] },
  { character: 'キ', answers: ['ki'] },
  { character: 'ク', answers: ['ku'] },
  { character: 'ケ', answers: ['ke'] },
  { character: 'コ', answers: ['ko'] },
  { character: 'サ', answers: ['sa'] },
  { character: 'シ', answers: ['shi', 'si'] },
  { character: 'ス', answers: ['su'] },
  { character: 'セ', answers: ['se'] },
  { character: 'ソ', answers: ['so'] },
  { character: 'タ', answers: ['ta'] },
  { character: 'チ', answers: ['chi', 'ti'] },
  { character: 'ツ', answers: ['tsu', 'tu'] },
  { character: 'テ', answers: ['te'] },
  { character: 'ト', answers: ['to'] },
  { character: 'ナ', answers: ['na'] },
  { character: 'ニ', answers: ['ni'] },
  { character: 'ヌ', answers: ['nu'] },
  { character: 'ネ', answers: ['ne'] },
  { character: 'ノ', answers: ['no'] },
  { character: 'ハ', answers: ['ha'] },
  { character: 'ヒ', answers: ['hi'] },
  { character: 'フ', answers: ['fu', 'hu'] },
  { character: 'ヘ', answers: ['he'] },
  { character: 'ホ', answers: ['ho'] },
  { character: 'マ', answers: ['ma'] },
  { character: 'ミ', answers: ['mi'] },
  { character: 'ム', answers: ['mu'] },
  { character: 'メ', answers: ['me'] },
  { character: 'モ', answers: ['mo'] },
  { character: 'ヤ', answers: ['ya'] },
  { character: 'ユ', answers: ['yu'] },
  { character: 'ヨ', answers: ['yo'] },
  { character: 'ラ', answers: ['ra'] },
  { character: 'リ', answers: ['ri'] },
  { character: 'ル', answers: ['ru'] },
  { character: 'レ', answers: ['re'] },
  { character: 'ロ', answers: ['ro'] },
  { character: 'ワ', answers: ['wa'] },
  { character: 'ヲ', answers: ['wo', 'o'] },
  { character: 'ン', answers: ['n'] },
  { character: 'ガ', answers: ['ga'] },
  { character: 'ギ', answers: ['gi'] },
  { character: 'グ', answers: ['gu'] },
  { character: 'ゲ', answers: ['ge'] },
  { character: 'ゴ', answers: ['go'] },
  { character: 'ザ', answers: ['za'] },
  { character: 'ジ', answers: ['ji', 'zi'] },
  { character: 'ズ', answers: ['zu'] },
  { character: 'ゼ', answers: ['ze'] },
  { character: 'ゾ', answers: ['zo'] },
  { character: 'ダ', answers: ['da'] },
  { character: 'ヂ', answers: ['ji', 'di'] },
  { character: 'ヅ', answers: ['zu', 'du'] },
  { character: 'デ', answers: ['de'] },
  { character: 'ド', answers: ['do'] },
  { character: 'バ', answers: ['ba'] },
  { character: 'ビ', answers: ['bi'] },
  { character: 'ブ', answers: ['bu'] },
  { character: 'ベ', answers: ['be'] },
  { character: 'ボ', answers: ['bo'] },
  { character: 'パ', answers: ['pa'] },
  { character: 'ピ', answers: ['pi'] },
  { character: 'プ', answers: ['pu'] },
  { character: 'ペ', answers: ['pe'] },
  { character: 'ポ', answers: ['po'] },
  { character: 'キャ', answers: ['kya'] },
  { character: 'キュ', answers: ['kyu'] },
  { character: 'キョ', answers: ['kyo'] },
  { character: 'シャ', answers: ['sha', 'sya'] },
  { character: 'シュ', answers: ['shu', 'syu'] },
  { character: 'ショ', answers: ['sho', 'syo'] },
  { character: 'チャ', answers: ['cha', 'tya', 'cya'] },
  { character: 'チュ', answers: ['chu', 'tyu', 'cyu'] },
  { character: 'チョ', answers: ['cho', 'tyo', 'cyo'] },
  { character: 'ニャ', answers: ['nya'] },
  { character: 'ニュ', answers: ['nyu'] },
  { character: 'ニョ', answers: ['nyo'] },
  { character: 'ヒャ', answers: ['hya'] },
  { character: 'ヒュ', answers: ['hyu'] },
  { character: 'ヒョ', answers: ['hyo'] },
  { character: 'ミャ', answers: ['mya'] },
  { character: 'ミュ', answers: ['myu'] },
  { character: 'ミョ', answers: ['myo'] },
  { character: 'リャ', answers: ['rya'] },
  { character: 'リュ', answers: ['ryu'] },
  { character: 'リョ', answers: ['ryo'] },
  { character: 'ギャ', answers: ['gya'] },
  { character: 'ギュ', answers: ['gyu'] },
  { character: 'ギョ', answers: ['gyo'] },
  { character: 'ジャ', answers: ['ja', 'jya', 'zya'] },
  { character: 'ジュ', answers: ['ju', 'jyu', 'zyu'] },
  { character: 'ジョ', answers: ['jo', 'jyo', 'zyo'] },
  { character: 'ヂャ', answers: ['ja', 'dya'] },
  { character: 'ヂュ', answers: ['ju', 'dyu'] },
  { character: 'ヂョ', answers: ['jo', 'dyo'] },
  { character: 'ビャ', answers: ['bya'] },
  { character: 'ビュ', answers: ['byu'] },
  { character: 'ビョ', answers: ['byo'] },
  { character: 'ピャ', answers: ['pya'] },
  { character: 'ピュ', answers: ['pyu'] },
  { character: 'ピョ', answers: ['pyo'] },
]

