#!/usr/bin/env python3
"""Generate a typed TypeScript data module from the frequency CSV file.

Usage:
  python3 data/generate_frequency_ts.py
  python3 data/generate_frequency_ts.py --input data/japanese_frequency_list.csv --output app/src/data/japaneseFrequencyData.ts
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a TypeScript array from a Japanese frequency CSV file.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/japanese_frequency_list.csv"),
        help="Path to source CSV file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("app/src/data/japaneseFrequencyData.ts"),
        help="Path to generated TypeScript file.",
    )
    return parser.parse_args()


def load_rows(csv_path: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []

    with csv_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)

        required_columns = {"Frequency", "Word", "Reading", "Type", "Meaning"}
        if reader.fieldnames is None or not required_columns.issubset(set(reader.fieldnames)):
            missing = required_columns.difference(set(reader.fieldnames or []))
            raise ValueError(f"CSV is missing required columns: {', '.join(sorted(missing))}")

        for index, raw_row in enumerate(reader, start=2):
            frequency_text = (raw_row.get("Frequency") or "").strip()
            if not frequency_text.isdigit():
                raise ValueError(
                    f"Invalid frequency '{frequency_text}' in row {index}. Frequency must be an integer."
                )

            rows.append(
                {
                    "frequency": int(frequency_text),
                    "word": (raw_row.get("Word") or "").strip(),
                    "reading": (raw_row.get("Reading") or "").strip(),
                    "type": (raw_row.get("Type") or "").strip(),
                    "meaning": (raw_row.get("Meaning") or "").strip(),
                }
            )

    return rows


def build_typescript_module(entries: list[dict[str, object]]) -> str:
    entries_json = json.dumps(entries, ensure_ascii=False, indent=2)

    return "\n".join(
        [
            "/* eslint-disable */",
            "// This file is auto-generated by data/generate_frequency_ts.py.",
            "// Do not edit by hand.",
            "",
            "export type JapaneseFrequencyEntry = {",
            "  frequency: number",
            "  word: string",
            "  reading: string",
            "  type: string",
            "  meaning: string",
            "}",
            "",
            f"export const japaneseFrequencyData: JapaneseFrequencyEntry[] = {entries_json}",
            "",
        ]
    )


def main() -> None:
    args = parse_args()
    input_path = args.input
    output_path = args.output

    if not input_path.exists():
        raise FileNotFoundError(f"Input CSV not found: {input_path}")

    entries = load_rows(input_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_typescript_module(entries), encoding="utf-8")

    print(f"Wrote {len(entries)} entries to {output_path}")


if __name__ == "__main__":
    main()
